name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: yarn
      - run: yarn install --frozen-lockfile
      - run: yarn format:check
      - run: yarn lint

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: yarn
      - run: yarn install --frozen-lockfile
      - run: yarn test

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [lint, test]
    env:
      MONGODB_URI: "mongodb://localhost:27017/bonby-test"
      AUTH_SECRET: "ci-test-secret-at-least-32-characters-long"
      NEXT_PUBLIC_APP_URL: "http://localhost:3000"
      NEXT_PUBLIC_APP_ENV: "development"
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: yarn
      - run: yarn install --frozen-lockfile
      - run: yarn build
